config/routes.rb
Bootstrap::Application.routes.draw do

  resources :notes

  get '/about'    => 'high_voltage/pages#show', id: 'about'
  get '/contact'  => 'high_voltage/pages#show', id: 'contact'
  get '/privacy'  => 'high_voltage/pages#show', id: 'privacy'
  get '/terms'    => 'high_voltage/pages#show', id: 'terms'
  get '/product'  => 'high_voltage/pages#show', id: 'product'

  get '/dog' =>  'high_voltage/pages#show', id: 'dog'
  get '/sendmail' =>  'high_voltage/pages#show', id: 'sendmail'

  get '/home', to: redirect('/')

  resources :notes

  root :to => 'high_voltage/pages#show', id: 'home'


end

app/models/note.rb
class Note < ActiveRecord::Base
	validates :name, :message, :presence => true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/notes_controller.rb
class NotesController < ApplicationController
  before_action :set_note, only: [:show, :edit, :update, :destroy]

  # GET /notes
  # GET /notes.json
  def index
    @notes = Note.all
  end

  # GET /notes/1
  # GET /notes/1.json
  def show
  end

  # GET /notes/new
  def new
    @note = Note.new
  end

  # GET /notes/1/edit
  def edit
  end

  # POST /notes
  # POST /notes.json
  def create
    @note = Note.new(note_params)

    respond_to do |format|
      if @note.save
        format.html { redirect_to @note, notice: 'Note was successfully created.' }
        format.json { render action: 'show', status: :created, location: @note }
      else
        format.html { render action: 'new' }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /notes/1
  # PATCH/PUT /notes/1.json
  def update
    respond_to do |format|
      if @note.update(note_params)
        format.html { redirect_to @note, notice: 'Note was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @note.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /notes/1
  # DELETE /notes/1.json
  def destroy
    @note.destroy
    respond_to do |format|
      format.html { redirect_to notes_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_note
      @note = Note.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def note_params
      params.require(:note).permit(:name, :message)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper

  def site_name
    "Menkey-League"
  end

  def site_url
    if Rails.env.production?
      # Place your production URL in the quotes below
      "https://menkey-league.herokuapp.com/"
    else
      # Our dev & test URL.
      "http://localhost:3000"
    end
  end

  def meta_author
    "Website Author"
  end

  def meta_description
    "Add your website descripiton here"
  end

  def meta_keywords
    "Add some keywords here"
  end

  # Returns the full title on a per-page basis.
  def full_title(page_title)
    if page_title.empty?
      site_name
    else
      "#{page_title} | #{site_name}"
    end
  end

end

app/helpers/notes_helper.rb
module NotesHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  
  <meta charset="utf-8">
  <meta http-equiv="X-UA-Compatible" content="IE=edge">
  <meta name="viewport" content="width=device-width, initial-scale=1.0">
  <meta name="description" content="<%= meta_description %>">
  <meta name="author" content="<%= meta_author %>">
  <meta name="Keywords" content="<%= meta_keywords %>">
  
  <title>Menkey-League</title>
  
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>

  <!-- HTML5 shim and Respond.js IE8 support of HTML5 elements and media queries -->
  <!--[if lt IE 9]>
    <script src="https://oss.maxcdn.com/libs/html5shiv/3.7.0/html5shiv.js"></script>
    <script src="https://oss.maxcdn.com/libs/respond.js/1.3.0/respond.min.js"></script>
  <![endif]-->
  <a href="#Top"></a>
</head>
<body>
  <div class="navbar navbar-fixed-top navbar-inverse" role="navigation">
    <div class="container">
      <div class="navbar-header ">
        <button type="button" class="navbar-toggle" data-toggle="collapse" data-target=".navbar-collapse">
          <span class="sr-only">Toggle navigation</span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
          <span class="icon-bar"></span>
        </button>
        <%= link_to site_name, site_url, :class => "navbar-brand" %>
      </div>
      <div class="collapse navbar-collapse">
        <ul class="nav navbar-nav pull-left">
          <li class="<%= 'active' if current_page?(root_path) %>"><%= link_to "主页", root_path %></li>
          <li class="<%= 'active' if current_page?(product_path) %>"><%= link_to "产品", product_path %></li>
          <li class="<%= 'active' if current_page?(contact_path) %>"><%= link_to "留言", notes_path %></li>
          <li class="<%= 'active' if current_page?(about_path) %>"><%= link_to "关于我", about_path %></li>
          <li class="dropdown">
            <a href="#" class="dropdown-toggle" data-toggle="dropdown">
               更多
               <b class="caret"></b>
            </a>
            <ul class="dropdown-menu">
               <li><%= link_to "Hack",  sendmail_path%></li>
               <li class="divider"></li>
               <li><%= link_to "Words", dog_path %></li>
            </ul>
         </li>
        </ul>
      </div><!-- /.nav-collapse -->
    </div><!-- /.container -->
  </div><!-- /.navbar -->

  <% if current_page?(root_path) %>
    <% if content_for?(:jumbotron) %>
      <div class="jumbotron">
        <div class="container">
          <%= yield :jumbotron %>
        </div>
      </div>
    <% end %>
    <% else %>
      <div class="container">
  <% end %>

    <%= yield %>
    <footer>
      <hr>
      <p class="pull-right">
        <%= link_to '<span class="glyphicon-class glyphicon glyphicon-chevron-up"></span> Back to top'.html_safe, '#Top' %>
      </p>
      <p>
        &copy; <%= Time.now.year %> <%= site_name %> 
        &bull;
        <%= link_to "Privacy", privacy_path %></li>
        &bull;
        <%= link_to "Terms", terms_path %></li>
      </p>
    </footer>
  </div> <!-- /container -->
</body>
</html>

app/views/notes/_form.html.erb
<%= form_for(@note) do |f| %>
  <% if @note.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@note.errors.count, "error") %> prohibited this note from being saved:</h2>

      <ul>
      <% @note.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="field">
    <%= f.label :message %><br>
    <%= f.text_area :message %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/notes/edit.html.erb
<h1>Editing note</h1>

<%= render 'form' %>

<%= link_to 'Show', @note %> |
<%= link_to 'Back', notes_path %>

app/views/notes/index.html.erb
<link href="stylesheets/custom.css" rel="stylesheet">
</br>
<div class="jumbotron">

   <div class="container">
      <h1>留下你想说的话</h1>
      <p>关于产品的意见，我一定认真听取。</p>
      <h3/>
      <p><%= link_to '<button class="btn btn-success btn-lg" type="button">留言</button>'.html_safe, new_note_path %>
      </p>
   </div>
</div>

<h2>留言板</h2>



<table class="table table-striped">
  <thead>
    <tr>
      <th>Name</th>
      <th>Message</th>
      <th>Created At</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @notes.each do |note| %>
      <tr>
        <td><%= note.name %></td>
        <td><%= note.message %></td>
        <td><%= note.created_at %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

app/views/notes/new.html.erb
<h1>留言</h1>

<%= render 'form' %>

<%= link_to 'Back', notes_path %>

app/views/notes/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @note.name %>
</p>

<p>
  <strong>Message:</strong>
  <%= @note.message %>
</p>

<%= link_to 'Edit', edit_note_path(@note) %> |
<%= link_to 'Back', notes_path %>

app/views/pages/about.html.erb
<% provide(:title, 'About Us') %>
<p></p> 
<link href="stylesheets/custom.css" rel="stylesheet">
<div class="jumbotron">

   <div class="row featurette">
        <div class="col-md-8">
        	<div class="col-md-4">
          	<img class="img-rounded img-responsive" src="images/wzp_009.jpg" alt="Generic placeholder image" width="160" height="160">
       		 </div>
          <h2 class="featurette-heading">韦泽鹏 <small><span class="label label-success"> 动效大师</span></small></h2>

          <h5>毕业于西北大学 本科</h5>
          <h5>生日 1992-3</h5>
          <h5>邮箱 tindle163@163.com</h5>
          <h5>手机 13572107241</h5>
        </div>
        
      </div>   
</div>

<h2>擅长技能<span class="label label-info"></span></h2>
<p>
<span class="label label-success">Android</span>  <span class="label label-danger">Ruby</span>  <span class="label label-warning">英语</span>
</p>
<h2> </h2>
<div class="list-group">
  <a href="#" class="list-group-item list-group-item-success">1. 熟悉Java Android, 擅长架构及UI特效，对Github，Twitter的许多开源项目比较熟悉</a>
  <a href="#" class="list-group-item list-group-item-info">2. 熟悉Ruby On Rails，掌握Bootstrap前端框架</a>
  <a href="#" class="list-group-item list-group-item-info">3. 会用JNI，NDK，反编译过Vine 微视等众多短视频应用，对视频及语音的底层有独特了解</a>
  <a href="#" class="list-group-item list-group-item-warning">4. 懂些Object-C，简单编写过IOS小程序</a>
  <a href="#" class="list-group-item list-group-item-danger">5. 英文CET－6，英语流利，阅读交流无障碍</a>
</div>

<br/>

<h2>个人项目<span class="label label-info"></span></h2>
<hr class="featurette-divider">
<div class="container marketing">

  <!-- MeowMeowBin -->
      <div class="row featurette">
        <div class="col-md-2">
          <img class="featurette-image img-responsive" src="images/meow_logo.png" alt="Generic placeholder image" width="180" height="180">
        </div>
        <div class="col-md-10">
          <h2 class="featurette-heading">喵喵必<small> <span class="label label-success"> 运营中</span></small></h2>
          <hr class="featurette-divider">
          <p class="lead">可以在小米应用市场和360应用市场搜索到</p>
        </div>
        
      </div>

      <br/>
    <!-- Content of GIF -->
      <div class="row ">
        <div class="col-lg-3 ">
          <img class="img-thumbnail" src="images/gif/meow_1.gif" alt="Generic placeholder image" >
          
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-3">
          <img class="img-thumbnail" src="images/gif/meow_2.gif" alt="Generic placeholder image" >
          
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-3">
          <img class="img-thumbnail" src="images/gif/meow_3.gif" alt="Generic placeholder image" >
          
        </div><!-- /.col-lg-4 -->

        <div class="col-lg-3">
          <img class="img-thumbnail" src="images/gif/meow_4.gif" alt="Generic placeholder image" >
          
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->
    </div>

    <!-- ManYouRen -->
    <br/>
    <br/>
    <br/>
    <br/>

      <div class="row featurette">
        <div class="col-md-2">
          <img class="featurette-image img-responsive" src="images/logo/myr_logo.png" alt="Generic placeholder image" width="180" height="180">
        </div>
        <div class="col-md-10">
          <h2 class="featurette-heading">漫游人 <small><span class="label label-danger"> 停止更新</span> <span class="label label-info">主流安卓市场可下载</span></small></h2>
          <hr class="featurette-divider">
          
          <a class="btn btn-info" href="https://github.com/TindleWei/ManYouRen" target="_blank">Github项目地址
          </a><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
        </div>
        
      </div>

      <br/>
    <!-- Content of GIF -->
      <div class="row ">
        <div class="col-lg-3 ">
          <img class="img-thumbnail" src="images/gif/n5.gif" alt="Generic placeholder image" >
          
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-3">
          
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-3">
          
        </div><!-- /.col-lg-4 -->

        <div class="col-lg-3">
          
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->
    </div>

</div>

<!-- ########################## -->

<div class="container marketing">
  <br/>
  <br/>
  <br/>
  <br/>
  <!-- MeowMeowBin -->
      <div class="row featurette">
        <div class="col-md-2">
          <img class="featurette-image img-responsive" src="images/logo/aweek_logo.png" alt="Generic placeholder image" width="180" height="180">
        </div>
        <div class="col-md-10">
          <h2 class="featurette-heading">一周 <small><span class="label label-danger"> 项目停止</span> <span class="label label-info">360应用市场可下载</span></small></h2>
          <hr class="featurette-divider">

          <a class="btn btn-info" href="https://github.com/TindleWei/Aweek-Deprecated" target="_blank">Github项目地址
          </a><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
        </div>
      </div>

      <br/>
    <!-- Content of GIF -->
      <div class="row ">
        <div class="col-lg-3 ">
          <img class="img-thumbnail" src="images/gif/n6.gif" alt="Generic placeholder image" >
          
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-3">
          <img class="img-thumbnail" src="images/gif/n7.gif" alt="Generic placeholder image" >
          
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-3">
          
        </div><!-- /.col-lg-4 -->

        <div class="col-lg-3">
          
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->

    <!-- ManYouRen -->
    <br/>
    <br/>
    <br/>
    <br/>

      <div class="row featurette">
        <div class="col-md-2">
          <img class="featurette-image img-responsive" src="images/logo/myj_logo.png" alt="Generic placeholder image" width="180" height="180">
        </div>
        <div class="col-md-10">
          <h2 class="featurette-heading">漫游家 <small><span class="label label-danger"> 项目停止</span> <span class="label label-info">360应用市场可下载</span></small></h2></small></h2>
          <hr class="featurette-divider">
          
          <a class="btn btn-info" href="https://github.com/TindleWei/ManYouJia" target="_blank">Github项目地址
          </a><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
        </div>
        
      </div>
      <br/>
    <!-- Content of GIF -->
      <div class="row ">
        <div class="col-lg-3 ">
          <img class="img-thumbnail" src="images/gif/n8.gif" alt="Generic placeholder image" >
          
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-3">
          <img class="img-thumbnail" src="images/gif/n9.gif" alt="Generic placeholder image" >
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-3">
          
        </div><!-- /.col-lg-4 -->

        <div class="col-lg-3">
          
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->
    </div>

</div


<!-- Others App-->
<div class="container marketing">
  <br/>
  <br/>
  <br/>
  <br/>
  <!-- MeowMeowBin -->
      <div class="row featurette">
        <div class="col-md-2">
          <img class="featurette-image img-responsive" src="images/logo/camily_logo.png" alt="Generic placeholder image" width="180" height="180">
        </div>
        <div class="col-md-10">
          <h2 class="featurette-heading">Camily <small><span class="label label-default"> 未上线</span></small></h2>
          <hr class="featurette-divider">
          
          <a class="btn btn-info" href="https://github.com/firefistwei/Camily-Pinterest" target="_blank">Github项目地址
          </a><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
        </div>
        
      </div>
  <br/>
  <br/>
  <!-- MeowMeowBin -->
      <div class="row featurette">
        <div class="col-md-2">
          <img class="featurette-image img-responsive" src="images/logo/tower_logo.png" alt="Generic placeholder image" width="180" height="180">
        </div>
        <div class="col-md-10">
          <h2 class="featurette-heading">灯塔 <small><span class="label label-default"> 未上线</span></small></h2>
          <hr class="featurette-divider">
          
          <a class="btn btn-info" href="https://github.com/firefistwei/LightTower-2.0" target="_blank">Github项目地址
          </a><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
        </div>
        
      </div>
  <br/>
  <br/>
      <div class="row featurette">
        <div class="col-md-2">
          <img class="featurette-image img-responsive" src="images/logo/u2b_logo.png" alt="Generic placeholder image" width="180" height="180">
        </div>
        <div class="col-md-10">
          <h2 class="featurette-heading">U2B <small><span class="label label-default"> 未上线</span> <span class="label label-info"> 360全国大学生应用开发大赛24强</span></small></h2>
          <hr class="featurette-divider">
          
          <a class="btn btn-info" href="https://github.com/firefistwei/U2B-2.0" target="_blank">Github项目地址
          </a><span class="glyphicon glyphicon-menu-right" aria-hidden="true"></span>
        </div>
        
      </div>
  <br/>
  <br/>

app/views/pages/contact.html.erb
<% provide(:title, 'Contact Us') %>

<link href="stylesheets/custom.css" rel="stylesheet">
</br>
<div class="jumbotron">

   <div class="container">
      <h1>留下你想说的话</h1>
      <p>关于产品的意见，我一定认真听取。</p>
      <p><a class="btn btn-primary btn-lg" role="button">
         留 言</a>
      </p>
   </div>
</div>

app/views/pages/dog.html.erb
<% provide(:title, 'Dog') %>
<link href="stylesheets/dog.css" rel="stylesheet">
<script src="javascripts/dog.js"></script>
<!-- wow -->
<div class="quote">
  <span class="line1">If you haven’t</span>
  <span class="line2">surprised</span>
  <span class="line3">yourself yet,</span>
  <span class="line4">you haven’t done</span>
  <span class="line5">enough</span>
  <span class="line6">sketching</span>
	</br>
  <cite>Tindle Wei</cite>
</div>

app/views/pages/home.html.erb
<% provide(:title, '') %>
<link href="stylesheets/custom.css" rel="stylesheet">
<link href="stylesheets/carousel.css" rel="stylesheet">
<% provide(:jumbotron, ' 
      <h1>Menkey-League</h1>
      <h4></h4>
      <p><h4>This is an organization of young generation.</h4></p>
      <h2></h2>
      <p>
      <a class="btn btn-primary btn-lg" href="product" role="button">关于联盟 &raquo;</a>
      </p>

  '.html_safe)%>
 <br/>
<!-- It works , button.
  <%= link_to '<button class="btn btn-primary btn-lg" type="button">New Post</button>'.html_safe, product_path %> -->


  <div class="container marketing">

    <!-- Three columns of text below the carousel -->
      <div class="row ">
        <div class="col-lg-4 ">
          <img class="img-circle" src="images/angrycat.jpg" alt="Generic placeholder image" width="140" height="140">
          <h2>MeowMeowBin</h2>
          <p>This an android app for cats.</p>
          <p><a class="btn btn-primary" href="product" role="button">详细 &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="images/djcat2.jpg" alt="Generic placeholder image" width="140" height="140">
          <h2>BigShow</h2>
          <p>A game which you can make your own slots.</p>
          <p><a class="btn btn-primary" href="product" role="button">详细 &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-4">
          <img class="img-circle" src="images/djcat.jpg" alt="Generic placeholder image" width="140" height="140">
          <h2>Sofar</h2>
          <p>A video platform that is in building.</p>
          <p><a class="btn btn-primary" href="product" role="button">详细 &raquo;</a></p>
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->
    

    <!-- Marketing messaging and featurettes
    ================================================== -->
    <!-- Wrap the rest of the page in another container to center all the content. -->

    <div class="container marketing">

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-7">
          <h2 class="featurette-heading">The First Product. <span class="text-muted">It'll strike your mind.</span></h2>
          <p class="lead">喵喵必中不仅仅有喵星人，还有喵喵Hub，喵喵Mix，喵喵Trans,<br>以及一切你能想到的的喵喵X。</p>
        </div>
        <div class="col-md-5">
          <img class="featurette-image img-responsive" src="images/grummycat.jpg" alt="Generic placeholder image">
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-5">
          <img class="featurette-image img-responsive" src="images/captain.jpg" alt="Generic placeholder image">
        </div>
        <div class="col-md-7">
          <h2 class="featurette-heading">Oh yeah, it's that good. <span class="text-muted">See for yourself.</span></h2>
          <p class="lead">加入门奇联盟你需要拥有两项能力: Coding & English<br>如果你向往我们要做的事，请告诉我，我会联系你的。</p>
        </div>
      </div>

      <hr class="featurette-divider">

      <div class="row featurette">
        <div class="col-md-4">
          <h2 class="featurette-heading">一起并肩作战 <span class="text-muted">My Friends</span></h2>
        </div>
        <div class="col-md-8">
          <img class="featurette-image img-responsive" src="images/avengers.jpg" alt="Generic placeholder image">
        </div>
      </div>

</div>

app/views/pages/privacy.html.erb
<% provide(:title, 'Privacy Policy') %>

<h1>Privacy Policy</h1>
<img class="img-rounded" src="https://twistedsifter.files.wordpress.com/2014/11/heroes-and-villains-as-flemish-portrait-paintings-by-sacha-goldberger-9.jpg" alt="Generic placeholder image" width="480" height="600">

app/views/pages/product.html.erb
<% provide(:title, 'Product') %>

<link href="stylesheets/carousel.css" rel="stylesheet">

</br>
<div id="myCarousel" class="carousel slide ">
   <!-- 轮播（Carousel）指标 -->
   <ol class="carousel-indicators">
      <li data-target="#myCarousel" data-slide-to="0" class="active"></li>
      <li data-target="#myCarousel" data-slide-to="1"></li>
      <!-- <li data-target="#myCarousel" data-slide-to="2"></li> -->
   </ol>   
   <!-- 轮播（Carousel）项目 -->
   <div class="carousel-inner">
      <div class="item active">
         <img src="/images/header.jpg" alt="First slide">
         <div class="carousel-caption">
          <img class="img-rounded" src="images/meow_logo.png" alt="Generic placeholder image" width="140" height="140">
              <h1>MeowMewoBin</h1>
              <p>This is an android app for cats which can change your voice.</p>
              <p><a class="btn btn-lg btn-success" href="#" role="button">Android 下载 <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span></a>
                <a class="btn btn-lg btn-default" href="#" role="button">IOS 制作中 <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span></a>
              </p>
        </div>
      </div>
      <div class="item">
         <img src="/images/header.jpg" alt="Second slide">
         <div class="carousel-caption">
          <img class="img-rounded" src="images/bigshow_logo.png" alt="Generic placeholder image" width="140" height="140">
              <h1>BigShow</h1>
              <p>Just in building.</p>
              <p><a class="btn btn-lg btn-primary" href="#" role="button">尽请期待 <span class="glyphicon glyphicon-download-alt" aria-hidden="true"></span></a>
              </p>
        </div>
      </div>
      <!-- <div class="item">
         <img src="/images/header.jpg" alt="Third slide">
         <div class="carousel-caption">标题 3</div>
      </div> -->
   </div>
   <!-- 轮播（Carousel）导航 -->
   <a class="left carousel-control" href="#myCarousel" role="button" data-slide="prev">
        <span class="glyphicon glyphicon-chevron-left" aria-hidden="true"></span>
        <span class="sr-only">Previous</span>
      </a>
      <a class="right carousel-control" href="#myCarousel" role="button" data-slide="next">
        <span class="glyphicon glyphicon-chevron-right" aria-hidden="true"></span>
        <span class="sr-only">Next</span>
      </a>
</div> 


<!-- This is about MeowMeowBin -->
 
 

<div class="container marketing">
  <p>
  <h2 class="featurette-heading2">MeowMeowBin <small><span class="text-muted">&nbsp;&nbsp;&nbsp;In Color Design</span><small></h2>
</p>
  <hr class="featurette-divider2">
    <!-- Three columns of text below the carousel -->
      <div class="row ">
        <div class="col-lg-3 ">
          <img class="img-thumbnail" src="images/meow_pic1.png" alt="Generic placeholder image" >
          
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-3">
          <img class="img-thumbnail" src="images/meow_pic2.png" alt="Generic placeholder image" >
          
        </div><!-- /.col-lg-4 -->
        <div class="col-lg-3">
          <img class="img-thumbnail" src="images/meow_pic3.png" alt="Generic placeholder image" >
          
        </div><!-- /.col-lg-4 -->

        <div class="col-lg-3">
          <img class="img-thumbnail" src="images/meow_pic4.png" alt="Generic placeholder image" >
          
        </div><!-- /.col-lg-4 -->
      </div><!-- /.row -->

    </div>
<div class="container marketing">
<br/>

<div class="panel panel-default">
  <!-- Default panel contents -->
  <div class="panel-heading"><b>喵喵必的介绍</b></div>
  <!-- List group -->
  <ul class="list-group">
    <li class="list-group-item">1. 喵喵必使用了欧洲最前沿技术的语音特效</li>
    <li class="list-group-item">2. 随着发喵的次数越来越多，你能发的声音种类也越来越多</li>
    <li class="list-group-item">3. 用它可以喵星人自由的对话，虽然不能保证不会打起来</li>
    <li class="list-group-item">4. 喵喵翻译机，喵喵混音器，喵喵变声党，一切你想不到的</li>
    <li class="list-group-item">5. 喵喵必暂时只有Android版在小米应用市场，IOS版哥正在做呢</li>
  </ul>
</div>
</div>